# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Cloud Marketplace Blog
tagline:          'by Ingram Micro'
description:      'Blog about Marketplace and stuff...'
url:              b-dap.github.com
paginate:         5

author:
  name:           'Ingram Micro'
  url:            http://ingrammicro.com

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/B-DAP/B-DAP.github.io
