# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ingram Micro
tagline:          'A Jekyll theme'
description:      'Testy Testy'
url:              b-dap.github.com

author:
  name:           'Pablo Roman'
  url:            www.google.ca

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
