# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            For Customers, By Customers
tagline:          'Blogy Blogy'
description:      'Impossible is a word to be only found in the dictionry of 					fools - Napoleon Bonaparte'
url:              b-dap.github.com
paginate:         5

author:
  name:           'Ingram Micro'
  url:            http://ingrammicro.com

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/B-DAP/B-DAP.github.io
