# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Cloud Marketplace Blog
tagline:          'by Ingram Micro'
description:      'Blog about Marketplace and stuff...'
url:              b-dap.github.com
paginate:         5

author:
  name:           'Alex Graciov'
  url:            http://google.ca

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
