# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Demo Blog
tagline:          'Blogy Blogy'
description:      'Brief Description of Blog'
url:              b-dap.github.com
paginate:         5

author:
  name:           'Alex Graciov'
  url:            https://github.com/B-DAP/B-DAP.github.io

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/B-DAP/B-DAP.github.io
